### PR TITLE
More precise typehint for value parameter of setCustomVariable

### LINKED ISSUE #2: More precise value type in setCustomVariable
Currently it is `mixed` which is quite vague.
In my early days with tideways I tried to set an array value, and it didn't work. :sweat_smile: 
It seems that it supports only `string|int|float|bool|null`, so maybe it could be a good idea to show that in the PHPDoc?

I can quickly work on a PR, but I can't confirm that the above type list is the right one

### PR DESCRIPTION
**Pull request by yguedidi**
fixes #2

setCustomVariable don't support arrays, but it support anything that can be casted to a string

### CODE REVIEW

**Comment by beberlei** [comment]
thank you @yguedidi !

**Comment by yguedidi** [comment]
you're welcome!

**Comment by yguedidi** [comment]
@beberlei could a release be tagged with this change? thanks

**Comment by tolry** [comment]
@yguedidi I released the patch under https://github.com/tideways/ext-tideways-stubs/releases/tag/v5.3.11.2

**Pull request merged**
